

#   欢迎加入-830841208-Java交流群
server:
  port: 8080
spring:
  application:
    name: temp_8080
  thymeleaf:
    suffix: .html
    cache: false    #页面不加载缓存，修改即时生效
  datasource:
    url: jdbc:mysql://rm-bp12dp9g0yluqn15uzo.mysql.rds.aliyuncs.com:3306/github_blog?&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: qun
    password: qun830841208-
  devtools:
    restart:
      enabled: true  #设置开启热部署