
#欢迎加入java架构交流学习群： 830841208

# 服务器配置
server:
  port: 80
#项目配置
spring:
  profiles:
    active: noteblogv4
  application:
    name: blog
  #资源配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  resources:
    static-locations: classpath:/static/
  #数据访问配置
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/github_blog?CharacterEncoding=UTF8&useSSL=false
#    username: root
#    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: me.wang-hai-cheng.noteblogv4.config.configuration.LocalMySQL57InnoDBDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  #最大上传文件大小
  servlet:
    multipart:
      max-file-size: 20MB
  cache:
    #使用默认的ConcurrentMap
    type: simple
    #程序启动时创建的缓存名称
    cache-names: paramCache,authCache
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    me:
      wang-hai-cheng:
        noteblogv4:
          dao:
            mapper: ERROR
